model_str: "kan_relu_interactions"
data_str:
  - "toxicity"
  - "titanic"
lr:
  - 0.0001
n_epochs:
  - 50
train_batch_size:
  - 64
relu_grid_size:
  - 5
relu_k:
  - 3
relu_apply_interactions:
  - [True, True, False, False]
  - [False, True, True, False]

widths:
  - [64,10, 5]
  - [100, 64, 10]
base_activation:
- "relu"
cuda: False
optimizer_str: "adam"
objective_str: "ce"
init_feature_extractor: False
layer_norm: False
relu_train_boundary: True
