
model_str: "kan_relu_interactions"
data_str:
  

  - "titanic"
 
lr:
  - 0.001
  - 0.0001
  - 0.00001
n_epochs:
  - 10
  
train_batch_size:
  
  - 64
  - 16
  
relu_grid_size:
  - 2
  - 5
  - 8
relu_k:
  - 2
  - 3
  - 5
relu_apply_interactions:
  - [False, False, False]
  - [True, True, False]
  - [False, True, False]

widths:

  - [128, 64]
  - [64, 32]
base_activation:
- "relu"
cuda: True
optimizer_str: "adam"
objective_str: "ce"
init_feature_extractor: False
layer_norm: False
relu_train_boundary: True
